Repository owncloud/brute_force_protection, pull requests merged in 2018-08, with the labels that each got.

#13 Update README.md
  README.md
Labels: 3 - To review

#11 Introduce php cs fixer
  .gitignore
  .php_cs.dist
  .travis.yml
  Makefile
  appinfo/Migrations/Version20180802194631.php
  appinfo/app.php
  composer.json
  composer.lock
  lib/AppInfo/Application.php
  lib/BruteForceProtectionConfig.php
  lib/Controller/SettingsController.php
  lib/Db/FailedLoginAttempt.php
  lib/Db/FailedLoginAttemptMapper.php
  lib/Hooks.php
  lib/Panels/AdminPanel.php
  lib/Throttle.php
  templates/settings-admin.php
  tests/BruteForceProtectionConfigTest.php
  tests/Controller/SettingsControllerTest.php
  tests/Db/FailedLoginAttemptMapperTest.php
  tests/HooksTest.php
  tests/ThrottleTest.php
  tests/bootstrap.php
Labels: 3 - To review, enhancement

#17 bootstrap UI tests
  .gitignore
  tests/acceptance/config/behat.yml
  tests/acceptance/features/bootstrap/BruteForceProtectionContext.php
  tests/acceptance/features/bootstrap/WebUIBruteForceProtectionContext.php
  tests/acceptance/features/bootstrap/bootstrap.php
  tests/acceptance/features/lib/BlockedUserPage.php
  tests/acceptance/features/lib/BruteForceProtectionPage.php
  tests/acceptance/features/webUIBruteForceProtection/bruteforceprotection.feature
Labels: 3 - To review, QA-team, dev:acceptance-tests

#19 first basic API acceptance tests
  tests/acceptance/config/behat.yml
  tests/acceptance/features/apiBruteForceProtection/bruteforceprotection.feature
  tests/acceptance/features/bootstrap/BruteForceProtectionContext.php
Labels: 3 - To review, QA-team, dev:acceptance-tests

#21 run API tests in drone
  .drone.yml
Labels: 3 - To review, QA-team

#24 No su exec www data
  .drone.yml
Labels: 3 - To review, QA-team

#22 more api tests
  .drone.yml
  tests/acceptance/features/apiBruteForceProtection/bruteforceprotection.feature
  tests/acceptance/features/bootstrap/BruteForceProtectionContext.php
Labels: 3 - To review, QA-team, dev:acceptance-tests
