Repository owncloud/brute_force_protection, pull requests merged in 2018-12, with the labels that each got.

#52 Standardize CI
  .drone.yml
  .phan/config.php
  .php_cs.dist
  Makefile
  composer.json
  composer.lock
  phpstan.neon
  phpunit.xml
  tests/unit/BruteForceProtectionConfigTest.php
  tests/unit/Controller/SettingsControllerTest.php
  tests/unit/Db/FailedLoginAttemptMapperTest.php
  tests/unit/HooksTest.php
  tests/unit/Jobs/ExpireOldAttemptsTest.php
  tests/unit/ThrottleTest.php
  vendor-bin/phan/composer.json
  vendor-bin/phpstan/composer.json
Labels: 3 - To review, QA-team

#55 use bootstrap.php of core acceptance tests
  tests/acceptance/features/bootstrap/bootstrap.php
Labels: 4 - To release, QA-team, dev:acceptance-tests

#56 Do not pin coding-standard to PHP 5.6
  vendor-bin/owncloud-codestyle/composer.json
Labels: 4 - To release, QA-team
