Repository owncloud/brute_force_protection, pull requests merged in 2020-04, with the labels that each got.

#113 line-ending code style fix
  templates/settings-admin.php
Labels: 3 - To review

#114 [Tests-Only] Update phpstan to latest version
  .drone.star
  composer.json
  composer.lock
  lib/BruteForceProtectionConfig.php
  lib/Db/FailedLoginAttempt.php
  lib/Hooks.php
  lib/Throttle.php
  phpstan.neon
  vendor-bin/phpstan/composer.json
Labels: 4 - To release, QA-team

#115 [Tests-Only] Bump phan 2.7
  vendor-bin/phan/composer.json
Labels: QA-team
