Repository owncloud/brute_force_protection, pull requests merged in 2020-06, with the labels that each got.

#126 Updating bamarni/composer-bin-plugin (1.4.0 => 1.4.1)
  composer.lock
Labels: 3 - To review

#128 Adjust phpstan.neon for phpstan 0.12.26 onwards
  phpstan.neon
Labels: 3 - To review, QA-team

#130 fix documentation path
  appinfo/info.xml
Labels: 4 - To release
