Repository owncloud/brute_force_protection, pull requests merged in 2020-12, with the labels that each got.

#143 [Tests-Only][CI] fix the starlark code for reduced ci after merge and sonarcloud
  .drone.star
  .gitignore
  sonar-project.properties
Labels: 3 - To review, QA-team

#144 [Tests-Only][CI] fix sonarcloud reporting in CI
  .drone.star
  sonar-project.properties
Labels: QA-team

#147 [tests-only] Add tests for upload and create folder in a public link
  tests/acceptance/features/apiBruteForceProtection/bruteforceprotection.feature
Labels: 3 - To review, QA-team, dev:acceptance-tests

#148 [tests-only] Implement latest .drone.star as at 2020-12-22
  .drone.star
  vendor-bin/behat/composer.json
  vendor-bin/php_codesniffer/composer.json
Labels: 3 - To review, QA-team
