Repository owncloud/brute_force_protection, pull requests merged in 2020-02, with the labels that each got.

#104 Use X-FORWADED-FOR header in Apache server
  .drone.starlark
  .drone.yml
Labels: 4 - To release, QA-team

#105 Use new owncloudci/oracle-xe docker image in CI
  .drone.starlark
  .drone.yml
Labels: 3 - To review, Drone, QA-team

#107 Change to .drone.star
  .drone.star
  .drone.yml
Labels: 3 - To review, Drone, QA-team

#108 [Tests-only] guzzle version updated
  vendor-bin/behat/composer.json
Labels: 3 - To review, QA-team

#109 fix make clean so it cleans the dependencies
  Makefile
Labels: 3 - To review, QA-team
